version: '3'

services:
  mariadb:
    image: library/mariadb:10.5
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      wordpress_mariadb_network:
      phpmyadmin_mariadb_network:

  phpmyadmin:
    image: iordaniskostelidis/phpmyadmin
    build:
      dockerfile: Dockerfile.phpmyadmin
      context: .
      args:
        PMA_DOMAIN_NAME: ${PMA_DOMAIN_NAME}
        WEBMASTER_EMAIL: ${WEBMASTER_EMAIL}
    container_name: phpmyadmin
    restart: unless-stopped
    volumes:
      - ./ssl_certificates:/docker/etc/apache2/ssl:ro
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    networks:
      phpmyadmin_mariadb_network:
      wordpress_phpmyadmin_network:

  wordpress:
    image: iordaniskostelidis/wordpress-on-docker
    build:
      dockerfile: ./Dockerfile.wordpress
      context: .
      args:
        WP_DOMAIN_NAME: ${WP_DOMAIN_NAME}
        PMA_DOMAIN_NAME: ${PMA_DOMAIN_NAME}
        WEBMASTER_EMAIL: ${WEBMASTER_EMAIL}
        PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
        PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
    container_name: wordpress
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./ssl_certificates:/docker/etc/apache2/ssl:ro
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - mariadb
    networks:
      wordpress_mariadb_network:
      wordpress_phpmyadmin_network:

volumes:
  mariadb_data:
  wordpress_data:

networks:
  wordpress_mariadb_network:
  phpmyadmin_mariadb_network:
  wordpress_phpmyadmin_network: